platform :ios, '16.0'

target 'NityaPooja' do
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK', '~> 12.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
