name: NityaPooja
options:
  bundleIdPrefix: com.nityapooja
  deploymentTarget:
    iOS: "16.0"
settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  NityaPooja:
    type: application
    platform: iOS
    sources:
      - iosApp
    configFiles:
      Debug: Debug.xcconfig
      Release: Release.xcconfig
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: LKBC2Y856Z
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: iosApp/Info.plist
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        PRODUCT_BUNDLE_IDENTIFIER: com.nityapooja.app
        SWIFT_VERSION: "5.0"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME) $(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/iphonesimulator26.2"
        OTHER_LDFLAGS: "$(inherited) -framework Shared"
    preBuildScripts:
      - name: "Build Kotlin Framework"
        script: |
          cd "$SRCROOT/.."
          if [ "$PLATFORM_NAME" = "macosx" ] || [ "$PLATFORM_NAME" = "" ]; then
            # Running on Mac (Designed for iPad) — build simulator framework and copy
            export SDK_NAME="iphonesimulator$(xcrun --sdk iphonesimulator --show-sdk-version)"
            export NATIVE_ARCH="arm64"
            export ARCHS="arm64"
            export PLATFORM_NAME="iphonesimulator"
            ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64
          else
            ./gradlew :shared:embedAndSignAppleFrameworkForXcode
          fi
        basedOnDependencyAnalysis: false
